### PR TITLE
Ruby 1.9 update

### PR DESCRIPTION
**Pull request by keithpitt**
I've updated the gem to work under Ruby 1.9 AND Ruby 1.8.x

I've also added some extra handling around the github_user and github_token methods that tell the user what to do in the event they don't exist (like when it happened to me :D)

All the specs pass and there are no warnings in 1.9.2p136

### CODE REVIEW

**Comment by kristianmandrup** [comment]
Great stuff!!!

**Comment by mdarby** [comment]
Can this be merged? Anyone?

**Comment by kristianmandrup** [comment]
OK, I just merged it into a new ruby-1.9 branch in my repo. Take it from there ... ;) if you dare!

**Comment by keithpitt** [comment]
One thing to note is that the gem is still backwards compatible with 1.8

The specs pass in both ruby-1.9.2-p136 and ruby-1.8.7-p302 on my machine.

Keith

**Comment by drnic** [comment]
Applied, thanks everyone.

**Pull request merged**
